# Generated by Django 5.2.6 on 2025-11-26 22:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Empresa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre de la Empresa')),
                ('gerente', models.CharField(max_length=100, verbose_name='Gerente General')),
                ('direccion', models.CharField(max_length=200, verbose_name='Dirección')),
                ('ubicacion_url', models.URLField(blank=True, null=True, verbose_name='Enlace Google Maps')),
                ('telefono', models.CharField(max_length=20, verbose_name='Teléfono de Contacto')),
                ('estado', models.BooleanField(default=True, verbose_name='Activo')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='empresa', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Cancha',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, verbose_name='Nombre de la Cancha')),
                ('capacidad', models.PositiveIntegerField(help_text='Ej: 10 para 5v5', verbose_name='Capacidad (Jugadores)')),
                ('precio_hora', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Precio por Hora')),
                ('estado', models.BooleanField(default=True)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='canchas', to='empresas.empresa')),
            ],
        ),
        migrations.CreateModel(
            name='FotoCancha',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagen', models.ImageField(upload_to='canchas/fotos/')),
                ('cancha', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fotos', to='empresas.cancha')),
            ],
        ),
    ]
