# Generated by Django 5.2.6 on 2025-11-12 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personas', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='persona',
            options={'ordering': ['user__username'], 'verbose_name': 'Persona', 'verbose_name_plural': 'Personas'},
        ),
        migrations.AlterField(
            model_name='persona',
            name='actualizado_en',
            field=models.DateTimeField(auto_now=True, verbose_name='Actualizado en'),
        ),
        migrations.AlterField(
            model_name='persona',
            name='apellido',
            field=models.CharField(blank=True, help_text='Apellido(s) de la persona.', max_length=30, null=True, verbose_name='Apellido'),
        ),
        migrations.AlterField(
            model_name='persona',
            name='celular',
            field=models.CharField(blank=True, help_text='Número de teléfono celular.', max_length=15, null=True, verbose_name='Celular'),
        ),
        migrations.AlterField(
            model_name='persona',
            name='creado_en',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Creado en'),
        ),
        migrations.AlterField(
            model_name='persona',
            name='direccion',
            field=models.CharField(blank=True, help_text='Dirección de residencia.', max_length=50, null=True, verbose_name='Dirección'),
        ),
        migrations.AlterField(
            model_name='persona',
            name='estado',
            field=models.BooleanField(default=True, help_text='Indica si el usuario está activo.', verbose_name='Estado'),
        ),
        migrations.AlterField(
            model_name='persona',
            name='fecha_nacimiento',
            field=models.DateField(blank=True, help_text='Fecha de nacimiento de la persona.', null=True, verbose_name='Fecha de Nacimiento'),
        ),
        migrations.AlterField(
            model_name='persona',
            name='genero',
            field=models.CharField(blank=True, choices=[('M', 'Masculino'), ('F', 'Femenino'), ('O', 'Otro')], help_text='Género de la persona.', max_length=1, null=True, verbose_name='Género'),
        ),
        migrations.AlterField(
            model_name='persona',
            name='nombre',
            field=models.CharField(blank=True, help_text='Nombre(s) de la persona.', max_length=30, null=True, verbose_name='Nombre'),
        ),
    ]
