# Generated by Django 5.2.6 on 2025-11-26 23:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personas', '0002_alter_persona_options_alter_persona_actualizado_en_and_more'),
    ]

    operations = [
        # migrations.AddField(
        #     model_name='persona',
        #     name='foto',
        #     field=models.ImageField(blank=True, help_text='Foto de perfil del usuario.', null=True, upload_to='personas/fotos/', verbose_name='Foto de Perfil'),
        # ),
        migrations.AddField(
            model_name='persona',
            name='rol',
            field=models.CharField(choices=[('CLIENTE', 'Cliente'), ('EMPRESARIO', 'Empresario')], default='CLIENTE', help_text='Define el rol del usuario en el sistema (Cliente o Empresario).', max_length=20, verbose_name='Rol de Usuario'),
        ),
    ]
