# Generated by Django 5.2.6 on 2025-11-28 16:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('personas', '0003_persona_foto'),
        ('personas', '0003_persona_foto_persona_rol'),
    ]

    operations = [
    ]
